site_name: HomeLab docs
site_url: https://docs.rodenlab.com
nav:
  - Home: index.md
  - About: about.md
  - Setup: setup.md

repo_url: https://github.com/felixroden/homelab-documentation
repo_name: felixroden/homelab-documentation

theme:
  name: 'material'
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
