site_name: Rodenlab docs
site_url: https://docs.rodenlab.com
nav:
  - Home: index.md
  - About: about.md
  - Setup: setup.md

theme:
  name: 'material'
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
